### ISSUE TITLE
we need a host for the database

### ISSUE THREAD

**Issue by ptwu** [ptwu/wwptechdesk#1]
https://www.nearlyfreespeech.net/ this is pretty cheap for low-traffic sites.
Any other hosts you guys know?

**Comment by Asap7772** [comment]
why are you making it? This was me and Mayaank’s job

**Comment by ptwu** [comment]
I'm helping out. I just missed the first meeting but I talked to Jimmy about it. That doesn't mean you can't help out at all, feel free to scrap my current homepage and front-end stuff if you want

**Comment by Asap7772** [comment]
Let’s talk tomorrow during lunch

**Comment by mayaankvad** [comment]
Peter is really good at this stuff so hes cool 👍. But this should stay only between the 3 of us now. No more inviting people. Also I have lab tomorrow :(

**Comment by Asap7772** [comment]
ok. Sounds good

**Comment by ptwu** [comment]
Yeah I made the logo with the table originally and talked to Jimmy way before. I'm not trying to get in the way of your efforts or anything

**Comment by mayaankvad** [comment]
No Peter, your fine. I think its better that you are on this now. Also the 3 of us and the leads have to have a live meeting before break.

**Comment by mayaankvad** [comment]
Or we could do a bit of cheating and set up our own server at school. <-- more on this later ;)

**Comment by Asap7772** [comment]
@ptwu Sorry, I just didn't know you were in the group. Lol. I think we'll be fine.

**Comment by Asap7772** [comment]
https://www.biz.nf
This can work
